"""Incremental base-and-delta search index primitives."""

from .models import (
    ChunkRef,
    CompactionPolicy,
    GenerationRecipe,
    LayerPosting,
    LegacyExportRecipe,
    SearchPosting,
    SearchViewRecipe,
    SegmentSummary,
    TokenSummary,
    ViewPin,
    logical_generation_core,
    logical_generation_id,
    make_doc_uid,
    validate_doc_key,
    validate_sha256,
)
from .source_diff import SegmentChangeSet, diff_segment_inputs
from .segment_projection import ChunkMetric, SegmentProjection, SegmentProjector
from .summary_store import (
    StoredSummaryRef,
    SummaryStoreError,
    load_summary,
    put_summary,
)
from .layer_codec import (
    LayerCodecError,
    LayerDocument,
    PostingLayerReader,
    PostingLayerReceipt,
    TermRecord,
    TokenContribution,
    write_posting_layer,
)
from .layer_runs import LayerRunError, StagedLayerBuilder, build_sorted_layer
from .generation import (
    LogicalGenerationError,
    LogicalGenerationReceipt,
    build_logical_generation,
    validate_logical_generation_inputs,
    validate_logical_generation_manifest,
)
from .statistics import CorpusTotals, TokenDfDelta, token_df_deltas
from .view_store import (
    BaseObjectReceipt,
    SearchViewReceipt,
    ViewDocumentOwner,
    ViewStoreConflictError,
    ViewStoreError,
    finalize_base_object,
    finalize_search_view,
    load_base_object,
    load_search_view,
    load_search_view_metadata,
    load_view_documents,
    write_base_candidate,
    write_search_view_candidate,
)
from .base_builder import build_base_view
from .delta_store import (
    DeltaObjectReceipt,
    DeltaStoreConflictError,
    DeltaStoreError,
    DocumentReplacement,
    StatisticsDelta,
    finalize_delta_object,
    load_delta_object,
    load_delta_object_metadata,
    write_delta_candidate,
)
from .delta_builder import (
    CompactionRecommendation,
    DeltaBuildResult,
    DeltaBuildWork,
    build_delta_view,
)
from .validator import (
    validate_base_normal,
    validate_delta_normal,
    validate_generation_normal,
    validate_view_normal,
)

__all__ = [
    "ChunkMetric",
    "ChunkRef",
    "BaseObjectReceipt",
    "CompactionPolicy",
    "CorpusTotals",
    "GenerationRecipe",
    "LayerPosting",
    "LayerCodecError",
    "LayerDocument",
    "LayerRunError",
    "LogicalGenerationError",
    "LogicalGenerationReceipt",
    "LegacyExportRecipe",
    "SearchPosting",
    "SearchViewReceipt",
    "SearchViewRecipe",
    "SegmentChangeSet",
    "SegmentProjection",
    "SegmentProjector",
    "SegmentSummary",
    "StoredSummaryRef",
    "StagedLayerBuilder",
    "PostingLayerReader",
    "PostingLayerReceipt",
    "SummaryStoreError",
    "TokenSummary",
    "TermRecord",
    "TokenContribution",
    "TokenDfDelta",
    "ViewPin",
    "ViewDocumentOwner",
    "ViewStoreConflictError",
    "ViewStoreError",
    "logical_generation_core",
    "logical_generation_id",
    "load_summary",
    "make_doc_uid",
    "put_summary",
    "write_posting_layer",
    "validate_doc_key",
    "diff_segment_inputs",
    "build_sorted_layer",
    "build_logical_generation",
    "build_base_view",
    "finalize_base_object",
    "finalize_search_view",
    "load_base_object",
    "load_search_view",
    "load_view_documents",
    "token_df_deltas",
    "validate_logical_generation_manifest",
    "validate_logical_generation_inputs",
    "validate_sha256",
    "write_base_candidate",
    "write_search_view_candidate",
    "CompactionRecommendation",
    "DeltaBuildResult",
    "DeltaBuildWork",
    "DeltaObjectReceipt",
    "DeltaStoreConflictError",
    "DeltaStoreError",
    "DocumentReplacement",
    "StatisticsDelta",
    "build_delta_view",
    "finalize_delta_object",
    "load_delta_object",
    "load_delta_object_metadata",
    "load_search_view_metadata",
    "write_delta_candidate",
    "validate_base_normal",
    "validate_delta_normal",
    "validate_generation_normal",
    "validate_view_normal",
]
